@echo off
REM ============================================================
REM  update-hobbies.bat
REM  Double-click this whenever you add / remove photos or videos
REM  in any  assets\Hobbies\<folder>.  It rewrites js\config\hobbies-media.js
REM  with the current file names. No manual editing needed.
REM ============================================================
setlocal enabledelayedexpansion
cd /d "%~dp0"

set "OUT=js\config\hobbies-media.js"
set "ROOT=assets\Hobbies"

if not exist "%ROOT%" (
  echo [!] Folder "%ROOT%" not found. Run this from your portfolio folder.
  pause
  exit /b 1
)

> "%OUT%" echo // AUTO-GENERATED by update-hobbies.bat  --  do not edit by hand.
>> "%OUT%" echo // Re-run the .bat after adding or removing media in assets\Hobbies.
>> "%OUT%" echo window.HOBBIES_MEDIA = {

set "FIRSTDIR=1"
for /d %%D in ("%ROOT%\*") do (
  set "FOLDER=%%~nxD"
  if "!FIRSTDIR!"=="1" ( set "FIRSTDIR=0" ) else ( >> "%OUT%" echo   , )
  >> "%OUT%" echo   "!FOLDER!": [
  set "FIRSTFILE=1"
  for %%F in ("%%D\*.jpg" "%%D\*.jpeg" "%%D\*.png" "%%D\*.gif" "%%D\*.webp" "%%D\*.mp4" "%%D\*.webm" "%%D\*.mov" "%%D\*.ogg") do (
    if exist "%%~fF" (
      if "!FIRSTFILE!"=="1" ( set "FIRSTFILE=0" ) else ( >> "%OUT%" echo     , )
      >> "%OUT%" echo     "%%~nxF"
    )
  )
  >> "%OUT%" echo   ]
)

>> "%OUT%" echo };

echo.
echo  Done!  Updated %OUT%
echo  Open hobbies.html to see the changes.
echo.
pause
