// AUTO-GENERATED by update-hobbies.bat  --  do not edit by hand.
// Re-run the .bat after adding or removing media in assets\Hobbies.
window.HOBBIES_MEDIA = {
  "Beach": [
    "IMG-20240626-WA0012.jpg.jpeg",
    "IMG-20240626-WA0014.jpg.jpeg",
    "IMG-20240629-WA0160.jpg.jpeg",
    "IMG-20240629-WA0209.jpg.jpeg",
    "IMG_20220808_194803-01-01.jpeg"
  ],
  "Cycling": [
    "1.jpeg",
    "2.jpeg",
    "3.jpeg",
    "4.jpeg",
    "5.jpeg",
    "aa.jpeg",
    "aaa.jpeg",
    "IMG-20240624-WA0178.jpg.jpeg",
    "IMG-20240624-WA0182.jpg.jpeg",
    "IMG-20240629-WA0210.jpg.jpeg",
    "IMG-20240629-WA0227.jpg.jpeg",
    "IMG-20240723-WA0021.jpg.jpeg",
    "VID-20240721-WA0139.mp4"
  ],
  "Dance": [
    "1.jpeg",
    "2.jpeg",
    "3.jpeg",
    "4.jpeg",
    "5.jpeg",
    "6.jpeg",
    "7.jpeg",
    "8.jpeg",
    "9.jpeg",
    "10.jpeg"
  ],
  "Sports": [
    "1.jpeg",
    "2.jpeg",
    "3.jpeg",
    "4.mp4",
    "5.mp4",
    "6.jpeg",
    "7.jpeg"
  ]
};
